sonar.projectKey=sample_python_github
sonar.projectName=sample-python-app
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.exclusions=**/sonar-scanner/**,**/*.zip,**/images/**,**/*.png,**/*.jpg,**/*.jpeg
