name: SonarQube Analysis

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  sonarcloud:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Extract branch name
        shell: bash
        run: echo "branch_name=${GITHUB_REF_NAME//\//-}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=my-project-${{ steps.extract_branch.outputs.branch_name }}
            -Dsonar.projectName=My Project (${{ github.ref_name }})
 
